name: Run All Tests

on:
  push:
    branches: [ main, node ]
  pull_request:
    branches: [ main, node ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout user code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}   # Change 'node' to '${{ github.ref }}'
          repository: vishnuathreya28/nano-demo-calculator-app

      - name: Navigate to repo directory
        run: cd nano-demo-calculator-app  # Change to your repository's directory

      - name: Run tests
        run: |
          newman_collectionName=calculator-tests iterationCount=1 web_app_cpu='2' test_driver_cpu='2' docker-compose -f compose-file.yml up --exit-code-from test-driver --build
